In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame({
    "age": [
        23,45,31,52,28,39,61,26,34,47,29,55,41,24,36,50,27,44,60,32
    ] * 50,

    "income": [
        3100,9200,4800,10500,3500,6700,12000,2900,5400,8800,
        4000,9800,7200,2600,6100,10000,3300,7900,11500,5000
    ] * 50,

    "active": [
        1,0,1,0,1,1,0,1,1,0,
        1,0,1,1,1,0,1,1,0,1
    ] * 50,

    "has_card": [
        0,1,0,1,0,1,1,0,0,1,
        0,1,1,0,1,1,0,1,1,0
    ] * 50,

    "region": [
        "A","C","B","C","A","B","C","A","B","C",
        "A","C","B","A","B","C","A","B","C","B"
    ] * 50,

    "device": [
        "mobile","web","both","web","mobile","both","web","mobile","mobile","web",
        "mobile","web","both","mobile","mobile","web","mobile","both","web","mobile"
    ] * 50
})

print(df.shape)
print(df.head())

(1000, 6)
   age  income  active  has_card region  device
0   23    3100       1         0      A  mobile
1   45    9200       0         1      C     web
2   31    4800       1         0      B    both
3   52   10500       0         1      C     web
4   28    3500       1         0      A  mobile

In [ ]:
y_binary = [
    0,1,0,1,0,0,1,0,0,1,
    0,1,0,0,0,1,0,1,1,0
] * 50

In [ ]:
df

     age  income  active  has_card region  device
0     23    3100       1         0      A  mobile
1     45    9200       0         1      C     web
2     31    4800       1         0      B    both
3     52   10500       0         1      C     web
4     28    3500       1         0      A  mobile
..   ...     ...     ...       ...    ...     ...
995   50   10000       0         1      C     web
996   27    3300       1         0      A  mobile
997   44    7900       1         1      B    both
998   60   11500       0         1      C     web
999   32    5000       1         0      B  mobile

[1000 rows x 6 columns]

In [ ]:
#Data preparation
df = pd.get_dummies(df)
df = df.astype(int)
df

,age,income,active,has_card,region_A,region_B,region_C,device_both,device_mobile,device_web
0,23,3100,1,0,1,0,0,0,1,0
1,45,9200,0,1,0,0,1,0,0,1
2,31,4800,1,0,0,1,0,1,0,0
3,52,10500,0,1,0,0,1,0,0,1
4,28,3500,1,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...
995,50,10000,0,1,0,0,1,0,0,1
996,27,3300,1,0,1,0,0,0,1,0
997,44,7900,1,1,0,1,0,1,0,0
998,60,11500,0,1,0,0,1,0,0,1
999,32,5000,1,0,0,1,0,0,1,0

In [ ]:
#Converting data frames to an array
x = df.to_numpy()
x = x - x.min(axis=0)/x.max(axis=0)-x.min(axis=0)

In [ ]:
w = np.zeros((x.shape[1],1))

y_binary = [
    0,1,0,1,0,0,1,0,0,1,
    0,1,0,0,0,1,0,1,1,0
] * 50

y_binary = pd.DataFrame(y_binary)

y_true = y_binary.to_numpy()
#Learning Factors
lr = 0.01
b = 0

y_true.shape
w.shape

(10, 1)

In [ ]:
#training loop
for i in range(200000) :
    z = x.dot(w) + b
    z = np.clip(z, -50, 50)
    #segmoid
    seg = 1/(1+np.exp(-z))
    error = seg - y_true
    gradient = x.T.dot(error)/x.shape[0]
    w = w - (lr*gradient)
    b = b - (lr*error.mean())

In [ ]:
print(w,b)

[[ 3.85604456e+01]
 [ 1.16900284e-02]
 [-3.05486806e+02]
 [ 4.92918602e+00]
 [-1.43251821e+02]
 [-1.62234986e+02]
 [ 8.04020929e+01]
 [-7.53406900e+01]
 [-2.30146116e+02]
 [ 8.04020929e+01]] -225.0847132922452

In [ ]:
x_test = x[0].copy()
x_test[0] = 60
x_test[1] = 7000
x_test = (x_test - x.min(axis=0))/(x.max(axis=0)-x.min(axis=0))

z_test = x_test.dot(w)+b
z_test = np.clip(z_test, -50, 50)
seg = 1/(1+np.exp(-z_test))
np.round(seg)

array([0.])

Here, based on the client's data, we predict whether they will leave the service or not.